services:
  # --- DATABASE ---
  db:
    platform: linux/arm64
    image: mariadb:11.4
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --max-connections=500
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: erpnext
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  # --- REDIS CACHE ---
  redis-cache:
    platform: linux/arm64
    image: redis:7-alpine
    restart: unless-stopped
    command: 
      - redis-server
      - --appendonly
      - "yes"
      - --maxmemory
      - 512mb
      - --maxmemory-policy
      - allkeys-lru
    volumes:
      - redis-cache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # --- REDIS QUEUE ---
  redis-queue:
    platform: linux/arm64
    image: redis:7-alpine
    restart: unless-stopped
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --maxmemory
      - 512mb
      - --maxmemory-policy
      - allkeys-lru
    volumes:
      - redis-queue-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # --- CONFIGURATOR (One-time setup) ---
  configurator:
    platform: linux/arm64
    image: frappe/erpnext:latest
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        echo "Configuring ERPNext...";
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
        echo "Configuration complete!"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"

  # --- SITE CREATOR (One-time setup) ---
  create-site:
    platform: linux/arm64
    image: frappe/erpnext:latest
    restart: "no"
    depends_on:
      configurator:
        condition: service_completed_successfully
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        echo "Waiting for services...";
        wait-for-it -t 120 db:3306;
        wait-for-it -t 60 redis-cache:6379;
        wait-for-it -t 60 redis-queue:6379;
        echo "Creating site...";
        bench new-site frappe.local 
        --no-mariadb-socket 
        --admin-password=admin 
        --db-root-password=admin 
        --install-app erpnext 
        --set-default;
        echo "Enabling scheduler...";
        bench --site frappe.local scheduler enable;
        bench --site frappe.local scheduler status;
        echo "Site creation complete!"

  # --- BACKEND ---
  backend:
    platform: linux/arm64
    image: frappe/erpnext:latest
    restart: unless-stopped
    depends_on:
      create-site:
        condition: service_completed_successfully
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  # --- WEBSOCKET ---
  websocket:
    platform: linux/arm64
    image: frappe/erpnext:latest
    restart: unless-stopped
    depends_on:
      create-site:
        condition: service_completed_successfully
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  # --- SCHEDULER ---
  scheduler:
    platform: linux/arm64
    image: frappe/erpnext:latest
    restart: unless-stopped
    depends_on:
      create-site:
        condition: service_completed_successfully
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  # --- WORKER: LONG QUEUE ---
  queue-long:
    platform: linux/arm64
    image: frappe/erpnext:latest
    restart: unless-stopped
    depends_on:
      create-site:
        condition: service_completed_successfully
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  # --- WORKER: SHORT QUEUE ---
  queue-short:
    platform: linux/arm64
    image: frappe/erpnext:latest
    restart: unless-stopped
    depends_on:
      create-site:
        condition: service_completed_successfully
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  # --- FRONTEND (NGINX) ---
  frontend:
    platform: linux/arm64
    image: frappe/erpnext:latest
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frappe.local
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-cache-data:
  redis-queue-data:
  sites:
  logs:
